-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 00:46:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL,
  `password` VARCHAR(45) NULL,
  `projectIDSubscribed` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Projects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Projects` (
  `ProjectId` INT NOT NULL,
  `ProjectName` VARCHAR(45) NOT NULL,
  `ShortDescription` VARCHAR(45) NOT NULL,
  `Users_idUsers` INT NOT NULL,
  `LongDescription` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  PRIMARY KEY (`ProjectId`),
  UNIQUE INDEX `ProjectId_UNIQUE` (`ProjectId` ASC) VISIBLE,
  UNIQUE INDEX `ProjectName_UNIQUE` (`ProjectName` ASC) VISIBLE,
  INDEX `fk_Projects_Users_idx` (`Users_idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_Projects_Users`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProjectFileLinks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProjectFileLinks` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProjectFileLinks` (
  `ProjectId` INT NULL,
  `FileLink` VARCHAR(45) NULL,
  `Projects_ProjectId` INT NOT NULL,
  PRIMARY KEY (`Projects_ProjectId`),
  CONSTRAINT `fk_ProjectFileLinks_Projects1`
    FOREIGN KEY (`Projects_ProjectId`)
    REFERENCES `mydb`.`Projects` (`ProjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
